version: '3.4'

services:
  czadruletapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
    image: ${DOCKER_REGISTRY-}czadruletapi
    build:
      context: .
      dockerfile: CzadRuletAPI/Dockerfile
